name: montycat
description: >
  Montycat Dart client: High-performance NoSQL client for Dart and Flutter with async operations, real-time subscriptions, in-memory and persistent storage.
version: 1.0.6
environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  hashlib: ^2.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - database
  - nosql
  - data-mesh
  - cache
  - realtime

license: MIT
homepage: https://montygovernance.com
documentation: https://pub.dev/documentation/montycat
