name: montycat
description: >
  The easiest NoSQL database client for Dart and Flutter with async operations, real-time events, and in-memory or persistent storage.

version: 1.0.3
environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  hashlib: ^2.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - database
  - nosql
  - data-mesh
  - cache
  - realtime

license: MIT
homepage: https://github.com/MontyGovernance/montycat_dart
repository: https://github.com/MontyGovernance/montycat_dart
# documentation: https://pub.dev/documentation/montycat
# publish_to: "https://pub.dev"
